
-- CRIAR PRIMEIRO TABELAS USUARIO E PERFIL
ALTER TABLE [dbo].[USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_USUARIO_PERFIL] FOREIGN KEY([IDPERFIL])
REFERENCES [dbo].[PERFIL] ([IDPERFIL])
GO

ALTER TABLE [dbo].[USUARIO] CHECK CONSTRAINT [FK_USUARIO_PERFIL]
GO