USE [PreventCataclysmSystems]
GO

CREATE TABLE [dbo].[LIVRO_USUARIO](
	[IDLIVRO_USUARIO] [INT] IDENTITY(1,1) NOT NULL,
	[IDUSUARIO] [INT] NOT NULL,
	[IDLIVROS] [INT] NOT NULL,
	[DTINICIO] [NVARCHAR](255) NOT NULL,
	[DTFINAL] [NVARCHAR](255) NOT NULL)

-- CRIAR PRIMEIRO AS TABELAS ANTES DE ALTERAR FK 

ALTER TABLE [dbo].[LIVRO_USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_LIVRO_USUARIO_LIVROS] FOREIGN KEY([IDLIVROS])
REFERENCES [dbo].[LIVROS] ([IDLIVROS])
GO

ALTER TABLE [dbo].[LIVRO_USUARIO] CHECK CONSTRAINT [FK_LIVRO_USUARIO_LIVROS]
GO

ALTER TABLE [dbo].[LIVRO_USUARIO]  WITH CHECK ADD  CONSTRAINT [FKUSUARIO_LIVRO_USUARIO] FOREIGN KEY([IDUSUARIO])
REFERENCES [dbo].[USUARIO] ([IDUSUARIO])
GO

ALTER TABLE [dbo].[LIVRO_USUARIO] CHECK CONSTRAINT [FKUSUARIO_LIVRO_USUARIO]
GO


