USE [PreventCataclysmSystems]
GO

CREATE TABLE [dbo].[LIVROS](
	[IDLIVROS] [INT] IDENTITY(1,1) NOT NULL,
	[NOME] [NVARCHAR](255) NOT NULL,
	[AUTOR] [NVARCHAR](255) NOT NULL,
	[SITUACAO] [BIT] NULL,
	[ESTADO] [NVARCHAR](50) NOT NULL,
	[ISBN] [VARCHAR](20) NOT NULL,
	[IDGENERO] [INT] NOT NULL
	)

-- CRIAR TABELA LIVROS E GENERO ANTES DE ALTERAR A FK

ALTER TABLE [dbo].[LIVROS]  WITH CHECK ADD  CONSTRAINT [FK_LIVROS_GENERO] FOREIGN KEY([IDGENERO])
REFERENCES [dbo].[GENERO] ([IDGENERO])
GO

ALTER TABLE [dbo].[LIVROS] CHECK CONSTRAINT [FK_LIVROS_GENERO]
GO


