CREATE TRIGGER TG_AUDITORIA_INSERT
ON dbo.LIVROS
AFTER INSERT
AS
      BEGIN
            SET NOCOUNT ON
     
            INSERT INTO dbo.AUDITORIA ( DATAALTERACAO , IDLIVRO , NOME , AUTOR , SITUACAO , ESTADO , ISBN , IDGENERO, INSTRUCAO )
            			   SELECT GETDATE(), IDLIVROS, NOME, AUTOR, SITUACAO, ESTADO, ISBN, IDGENERO, 'INSERT' FROM INSERTED 
      END
GO
