CREATE TRIGGER TG_AUDITORIA_UPDATE
ON dbo.LIVROS
AFTER UPDATE
AS
      BEGIN
            SET NOCOUNT ON
     
            INSERT INTO dbo.AUDITORIA ( DATAALTERACAO , IDLIVRO , NOME , AUTOR , SITUACAO , ESTADO , ISBN , IDGENERO, INSTRUCAO )
            			   SELECT GETDATE(), IDLIVROS, NOME, AUTOR, SITUACAO, ESTADO, ISBN, IDGENERO, 'UPDATE' FROM INSERTED 
      END
GO