CREATE TRIGGER TG_AUDITORIA_DELETE
ON dbo.LIVROS
AFTER DELETE
AS
      BEGIN
            SET NOCOUNT ON
     
            INSERT INTO dbo.AUDITORIA ( DATAALTERACAO , IDLIVRO , NOME , AUTOR , SITUACAO , ESTADO , ISBN , IDGENERO, INSTRUCAO )
            			   SELECT GETDATE(), IDLIVROS, NOME, AUTOR, SITUACAO, ESTADO, ISBN, IDGENERO, 'DELETE' FROM INSERTED 
      END
GO
